### ISSUE TITLE
'validateAddress' issue?

### ISSUE THREAD

**Issue by lat9** [taxjar/taxjar-php#21]
I've loaded v1.8.0 into a working copy and tried to use the `validateAddress` method just included using the values used in the unittest:

```php
$client = TaxJar\Client::withApiKey(TAXJAR_API_KEY);
$validation = $client->validateAddress(array(
            'country' => 'US',
            'state' => 'AZ',
            'zip' => '85297',
            'city' => 'Gilbert',
            'street' => '3301 South Greenfield Rd'));
```

I'm receiving the following in a PHP error log:
```
[02-Nov-2018 11:24:14 America/New_York] PHP Fatal error:  Uncaught TaxJar\Exception: 401  –  in C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\lib\TaxJar.php:36
Stack trace:
#0 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\FulfilledPromise.php(39): TaxJar\TaxJar->TaxJar\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}()
#2 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Promise\TaskQueue->run(true)
#3 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#4 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#5 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#6 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#7 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\guzzle\src\Client.php(131): GuzzleHttp\Promise\Promise->wait()
#8 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\vendor\guzzlehttp\guzzle\src\Client.php(89): GuzzleHttp\Client->request('post', 'addresses/valid...', Array)
#9 C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\lib\Client.php(314): GuzzleHttp\Client->__call('post', Array)
#10 C:\xampp\htdocs\taxjartest\test_taxjar.php(21): TaxJar\Client->validateAddress(Array)
#11 {main}
  thrown in C:\xampp\htdocs\taxjartest\includes\classes\vendors\TaxJar\lib\TaxJar.php on line 36
```

Note that the `TAXJAR_API_KEY` is valid and defined correctly, as I'm able to receive output from the `categories` method.

**Comment by fastdivision** [comment]
Hi @lat9, at the moment this endpoint is available for [TaxJar Plus](https://www.taxjar.com/plus/) customers only. I apologize for the lack of documentation. Address validation is currently in beta and the documentation is being shared privately. In order to onboard beta customers faster via Composer, we added the `validateAddress` method to our API client. If you're interested in signing up for TaxJar Plus to use address validation, please [reach out](https://www.taxjar.com/contact/) to our support team and we'll get you into the beta right away. If you're building a PHP integration for others to use, [submit your integration](https://developers.taxjar.com/integrations/submit/) and include a note about address validation. We'll figure out how to get you access. Thank you!

**Comment by lat9** [comment]
Ah, no problems.  If that functionality was in the base offering, I'd be using it.  Thanks for the clarification.
