### ISSUE TITLE
TaxJar\Client->createOrder() throws "GuzzleHttp\Exception\ClientException" with "Client error: 422".

### ISSUE THREAD

**Issue by budhajeewa** [taxjar/taxjar-php#7]
`TaxJar\Client->createOrder()` throws `GuzzleHttp\Exception\ClientException`  with `Client error: 422`.

Code worked fine Friday evening, and it is broken now in Monday morning (Office was closed for the weekend and the local wich-doctor assures there's no ghosts here :wink:.).

Following is the stack trace:

```
#0 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#2 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#3 __PROJECT_ROOT__/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\Promise\TaskQueue->run()
#4 __PROJECT_ROOT__/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(123): GuzzleHttp\Handler\CurlMultiHandler->tick()
#5 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(240): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#6 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(217): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(261): GuzzleHttp\Promise\Promise->waitIfPending()
#8 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(219): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 __PROJECT_ROOT__/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 __PROJECT_ROOT__/vendor/guzzlehttp/guzzle/src/Client.php(130): GuzzleHttp\Promise\Promise->wait()
#11 __PROJECT_ROOT__/vendor/guzzlehttp/guzzle/src/Client.php(88): GuzzleHttp\Client->request('post', 'transactions/or...', Array)
#12 __PROJECT_ROOT__/vendor/taxjar/taxjar-php/lib/Client.php(94): GuzzleHttp\Client->__call('post', Array)
#13 __PROJECT_ROOT__/vendor/taxjar/taxjar-php/lib/Client.php(94): GuzzleHttp\Client->post('transactions/or...', Array)
#14 __PROJECT_ROOT__/app/Providers/Tax/TaxJar/TaxService.php(69): TaxJar\Client->createOrder(Array)
```

Following is the debug log:

```
* Hostname was NOT found in DNS cache
* Trying 204.236.224.144...
* Connected to api.taxjar.com (204.236.224.144) port 443 (#6)
* successfully set certificate verify locations: 
* CAfile: none CApath: /etc/ssl/certs 
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256 
* Server certificate: 
* subject: OU=Domain Control Validated; CN=api.taxjar.com 
* start date: 2014-09-23 14:43:22 GMT 
* expire date: 2016-09-23 14:43:22 GMT 
* subjectAltName: api.taxjar.com matched 
* issuer: C=US; ST=Arizona; L=Scottsdale; O=GoDaddy.com, Inc.; OU=http://certs.godaddy.com/repository/; CN=Go Daddy Secure Certificate Authority - G2 
* SSL certificate verify ok. 

> POST /v2/taxes HTTP/1.1 Authorization: Bearer __API_KEY__ User-Agent: GuzzleHttp/6.0.2 curl/7.35.0 PHP/5.5.9-1ubuntu4.12 Content-Type: application/json Host: api.taxjar.com Content-Length: 142 
* upload completely sent off: 142 out of 142 bytes 
< HTTP/1.1 200 OK 
* Server Cowboy is not blacklisted 
< Server: Cowboy 
< Connection: keep-alive 
< Date: Tue, 29 Sep 2015 02:23:53 GMT 
< Status: 200 OK 
< Content-Type: application/json 
< Content-Length: 181 
< Vary: Origin 
< Etag: "ec670ee2dd3793e90fec6e9f299ee3ee" 
< Cache-Control: max-age=0, private, must-revalidate 
< X-Request-Id: 7cc5c3d1-6810-48f2-8162-6303a9d15997 
< X-Runtime: 0.041539 
< Via: 1.1 vegur 
< 
* Connection #6 to host api.taxjar.com left intact 
* Found bundle for host api.taxjar.com: 0x7f397c276860 
* Re-using existing connection! (#6) with host api.taxjar.com 
* Connected to api.taxjar.com (204.236.224.144) port 443 (#6)

> POST /v2/transactions/orders HTTP/1.1 Authorization: Bearer __API_KEY__ User-Agent: GuzzleHttp/6.0.2 curl/7.35.0 PHP/5.5.9-1ubuntu4.12 Content-Type: application/json Host: api.taxjar.com Content-Length: 273 
* upload completely sent off: 273 out of 273 bytes 
< HTTP/1.1 422 Unprocessable Entity 
* Server Cowboy is not blacklisted 
< Server: Cowboy 
< Connection: keep-alive 
< Date: Tue, 29 Sep 2015 02:23:54 GMT 
< Status: 422 Unprocessable Entity 
< Content-Type: application/json 
< Content-Length: 89 
< Vary: Origin 
< Cache-Control: no-cache 
< X-Request-Id: 729d3cf9-1a76-43eb-aca3-f2e056fe1232 
< X-Runtime: 0.323102 
< Via: 1.1 vegur 
< 
* Connection #6 to host api.taxjar.com left intact 
```

**Comment by budhajeewa** [comment]
I think I caught the culprit: I am sending duplicate `transaction_id`s.

This is because I am still developing the application, and I often reset the database, causing it to generate IDs that were previously used.

It'll be great if there is a way for me to delete old testing transactions from your system, through the dashboard.

Also, it would have been useful if the error message pinpointed the exact problem.

One more problem, although I deleted the transactions through the API, and the dashboard no longer shows them, "Sales Tax Report" still shows the amounts collected from deleted transactions.

**Comment by tonkapark** [comment]
Yes, you will get an error when trying to create an order with the ID that already exists in TaxJar for your account. We will look at better messaging. You can list your orders via the API, then delete them, http://developers.taxjar.com/api/#transactions

For account specific questions we recommend contacting support@taxjar.com
